/**
 * Personal document types, grouped by the country that issues them.
 *
 * These are deliberately specific: a residence permit and a birth certificate
 * have almost nothing in common beyond "it is paper", and typing the issuing
 * authority into a generic "notes" box is how a document becomes unfindable
 * three years later. Fields left blank never render, so a rich schema costs
 * nothing to whoever only fills two of them.
 *
 * Credentials are deliberately absent — a tax-portal password belongs in the
 * `login` type, which tracks 2FA and rotates on its own cadence.
 */
import type { SecretTypeDef } from './model';

/** Where a document group comes from; drives the wizard's origin step. */
export interface DocumentOrigin {
  group: string;
  /** Two-letter tile shown in place of a flag (emoji stay out of the UI). */
  code: string;
  accent: string;
  hint: string;
}

export const GENERAL_GROUP = 'Geral';

export const DOCUMENT_ORIGINS: DocumentOrigin[] = [
  { group: 'Portugal', code: 'PT', accent: '#34d399', hint: 'Título de residência, CC, NIF, NISS…' },
  { group: 'Brasil', code: 'BR', accent: '#fbbf24', hint: 'CPF, RG, CNH, título de eleitor, certidões…' },
  { group: 'Espanha', code: 'ES', accent: '#c084fc', hint: 'DNI, NIE/TIE, Seguridad Social…' },
  { group: 'Estados Unidos', code: 'US', accent: '#38bdf8', hint: 'SSN, Green Card, Driver’s License…' },
  { group: 'França', code: 'FR', accent: '#f472b6', hint: 'CNI, Titre de Séjour, Sécurité Sociale…' },
  { group: 'Alemanha', code: 'DE', accent: '#a3e635', hint: 'Personalausweis, Aufenthaltstitel, Steuer-ID…' },
  { group: 'Itália', code: 'IT', accent: '#22d3ee', hint: 'Carta d’Identità, Codice Fiscale, Permesso…' },
  { group: 'Reino Unido', code: 'GB', accent: '#7c9cff', hint: 'NI Number, BRP/eVisa, Driving Licence…' },
];

/**
 * A family collapses near-identical paperwork into ONE entry in the type list,
 * with the specific kind chosen inside the form — declarations are the case
 * that forced it: seven separate tiles for what a person thinks of as "uma
 * declaração". The specific forms stay specific (that is the whole product
 * promise); only the way you reach them is folded.
 */
export interface TypeFamily {
  id: string;
  label: string;
  description: string;
  icon: string;
  accent: string;
  /** Label of the picker rendered inside the form. */
  pickerLabel: string;
  /** Member used when the family is picked before the specific kind is known. */
  defaultTypeId: string;
}

/** The origin behind a stored country code, if it is one we know. */
export function originByCode(code: string): DocumentOrigin | undefined {
  return DOCUMENT_ORIGINS.find((origin) => origin.code === code);
}

export const TYPE_FAMILIES: TypeFamily[] = [
  {
    id: 'declaracoes',
    label: 'Declarações',
    description: 'IRS, nado vivo, crédito, situação contributiva… escolhe-se no formulário.',
    icon: 'file',
    accent: '#e8b45a',
    pickerLabel: 'Tipo de declaração',
    defaultTypeId: 'declaracao',
  },
];

export const DOCUMENT_TYPES: SecretTypeDef[] = [
  // ---- Portugal -----------------------------------------------------------
  {
    id: 'pt-residencia',
    namePlaceholder: 'Título de residência — Maria',
    label: 'Título de residência',
    keywords: ['AIMA', 'SEF', 'autorização de residência', 'imigração', 'residência'],
    group: 'Portugal',
    category: 'doc',
    description: 'Autorização de residência emitida pela AIMA/SEF, por emissão.',
    icon: 'idCard',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número do título', kind: 'text' },
      { id: 'tipoAutorizacao', label: 'Tipo de autorização', kind: 'text', placeholder: 'Temporária · Permanente · CPLP' },
      { id: 'entidade', label: 'Entidade emissora', kind: 'text', placeholder: 'AIMA' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'processo', label: 'Número do processo', kind: 'text' },
      { id: 'observacoes', label: 'Observações', kind: 'multiline' },
    ],
  },
  {
    id: 'pt-cartao-cidadao',
    namePlaceholder: 'Cartão de Cidadão — Maria',
    label: 'Cartão de Cidadão',
    keywords: ['CC', 'cartão do cidadão', 'identidade', 'documento de identidade'],
    group: 'Portugal',
    category: 'doc',
    description: 'Documento de identificação português, com os números que ele agrega.',
    icon: 'idCard',
    accent: '#22d3ee',
    fields: [
      { id: 'civilId', label: 'Nº de identificação civil', kind: 'text', numeric: true },
      { id: 'documentNumber', label: 'Nº do documento', kind: 'text', hint: 'Inclui a versão, ex.: 12345678 9 ZZ1' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'nif', label: 'NIF', kind: 'text', numeric: true },
      { id: 'niss', label: 'NISS', kind: 'text', numeric: true },
      { id: 'sns', label: 'Nº de utente (SNS)', kind: 'text', numeric: true },
    ],
  },
  {
    id: 'pt-nif',
    namePlaceholder: 'NIF — Maria',
    label: 'NIF',
    keywords: ['contribuinte', 'número de contribuinte', 'número fiscal', 'finanças', 'AT'],
    group: 'Portugal',
    category: 'doc',
    description: 'Número de identificação fiscal português.',
    icon: 'stamp',
    accent: '#fbbf24',
    fields: [
      { id: 'nif', label: 'NIF', kind: 'text', placeholder: '123456789', numeric: true },
      { id: 'servicoFinancas', label: 'Serviço de finanças', kind: 'text' },
      { id: 'representante', label: 'Representante fiscal', kind: 'text' },
      { id: 'issuedAt', label: 'Atribuído em', kind: 'date' },
    ],
  },
  {
    id: 'pt-niss',
    namePlaceholder: 'NISS — Maria',
    label: 'NISS',
    keywords: ['segurança social', 'número de segurança social'],
    group: 'Portugal',
    category: 'doc',
    description: 'Número de identificação da Segurança Social.',
    icon: 'stamp',
    accent: '#a3e635',
    fields: [
      { id: 'niss', label: 'NISS', kind: 'text', numeric: true },
      { id: 'issuedAt', label: 'Atribuído em', kind: 'date' },
    ],
  },
  {
    id: 'pt-utente',
    namePlaceholder: 'Nº de utente — Maria',
    label: 'Nº de utente (SNS)',
    keywords: ['SNS', 'saúde', 'centro de saúde', 'número de utente'],
    group: 'Portugal',
    category: 'doc',
    description: 'Número de utente do Serviço Nacional de Saúde.',
    icon: 'health',
    accent: '#f472b6',
    fields: [
      { id: 'numeroUtente', label: 'Nº de utente', kind: 'text', numeric: true },
      { id: 'centroSaude', label: 'Centro de saúde', kind: 'text' },
      { id: 'medicoFamilia', label: 'Médico de família', kind: 'text' },
    ],
  },
  {
    id: 'pt-registo-criminal',
    namePlaceholder: 'Registo criminal — nacionalidade',
    label: 'Registo criminal',
    keywords: ['antecedentes criminais', 'certidão negativa', 'nada consta'],
    group: 'Portugal',
    category: 'doc',
    description: 'Certificado de registo criminal — costuma ter validade curta.',
    icon: 'scale',
    accent: '#c084fc',
    fields: [
      { id: 'documentNumber', label: 'Nº do certificado', kind: 'text' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text', placeholder: 'Nacionalidade · Emprego' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'pt-morada',
    namePlaceholder: 'Comprovativo de morada — 2026',
    label: 'Comprovativo de morada',
    keywords: ['comprovante de endereço', 'atestado de residência', 'junta de freguesia'],
    group: 'Portugal',
    category: 'doc',
    description: 'Atestado de junta de freguesia, fatura ou equivalente.',
    icon: 'home',
    accent: '#7c9cff',
    fields: [
      { id: 'tipoComprovativo', label: 'Tipo', kind: 'text', placeholder: 'Atestado de residência · Fatura' },
      { id: 'morada', label: 'Morada', kind: 'multiline' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
    ],
  },
  {
    id: 'pt-arrendamento',
    namePlaceholder: 'Arrendamento — Rua das Flores',
    label: 'Contrato de arrendamento',
    keywords: ['aluguel', 'aluguer', 'senhorio', 'inquilino', 'renda'],
    group: 'Portugal',
    category: 'doc',
    description: 'Contrato de habitação, com prazos e renda.',
    icon: 'home',
    accent: '#fb923c',
    fields: [
      { id: 'morada', label: 'Morada', kind: 'multiline' },
      { id: 'senhorio', label: 'Senhorio', kind: 'text' },
      { id: 'contractNumber', label: 'Nº do contrato / recibo', kind: 'text' },
      { id: 'startsAt', label: 'Início', kind: 'date' },
      { id: 'endsAt', label: 'Fim', kind: 'date' },
      { id: 'renda', label: 'Renda mensal', kind: 'text' },
    ],
  },

  // ---- Brasil -------------------------------------------------------------
  {
    id: 'br-cpf',
    namePlaceholder: 'CPF — Maria',
    label: 'CPF',
    keywords: ['receita federal', 'cadastro de pessoa física', 'número fiscal', 'contribuinte'],
    group: 'Brasil',
    category: 'doc',
    description: 'Cadastro de Pessoas Físicas.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'cpf', label: 'CPF', kind: 'text', placeholder: '000.000.000-00', numeric: true },
      { id: 'situacao', label: 'Situação cadastral', kind: 'text', placeholder: 'Regular' },
      { id: 'issuedAt', label: 'Inscrição em', kind: 'date' },
    ],
  },
  {
    id: 'br-rg',
    namePlaceholder: 'RG — Maria',
    label: 'RG',
    keywords: ['identidade', 'carteira de identidade', 'documento de identidade'],
    group: 'Brasil',
    category: 'doc',
    description: 'Registro Geral / carteira de identidade.',
    icon: 'idCard',
    accent: '#38bdf8',
    fields: [
      { id: 'rgNumber', label: 'Número', kind: 'text' },
      { id: 'orgaoEmissor', label: 'Órgão emissor', kind: 'text', placeholder: 'SSP' },
      { id: 'uf', label: 'UF', kind: 'text', placeholder: 'RJ' },
      { id: 'issuedAt', label: 'Data de expedição', kind: 'date' },
    ],
  },
  {
    id: 'br-cnh',
    namePlaceholder: 'CNH — Maria',
    label: 'CNH',
    keywords: ['carteira de motorista', 'habilitação', 'carta de condução', 'detran'],
    group: 'Brasil',
    category: 'doc',
    description: 'Carteira Nacional de Habilitação.',
    icon: 'car',
    accent: '#fbbf24',
    fields: [
      { id: 'registro', label: 'Nº de registro', kind: 'text', numeric: true },
      { id: 'numeroEspelho', label: 'Nº do espelho', kind: 'text', numeric: true },
      { id: 'categoria', label: 'Categoria', kind: 'text', placeholder: 'AB' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'primeiraHabilitacao', label: 'Primeira habilitação', kind: 'date' },
    ],
  },
  {
    id: 'br-titulo-eleitor',
    namePlaceholder: 'Título de eleitor — Maria',
    label: 'Título de eleitor',
    keywords: ['justiça eleitoral', 'zona', 'seção', 'eleitoral'],
    group: 'Brasil',
    category: 'doc',
    description: 'Inscrição eleitoral, zona e seção.',
    icon: 'stamp',
    accent: '#818cf8',
    fields: [
      { id: 'numero', label: 'Nº de inscrição', kind: 'text', numeric: true },
      { id: 'zona', label: 'Zona', kind: 'text', numeric: true },
      { id: 'secao', label: 'Seção', kind: 'text', numeric: true },
      { id: 'municipio', label: 'Município', kind: 'text' },
      { id: 'uf', label: 'UF', kind: 'text' },
    ],
  },
  {
    id: 'br-certidao',
    namePlaceholder: 'Certidão de nascimento — Helena',
    label: 'Certidão de registo civil',
    keywords: ['certidão de nascimento', 'certidão de casamento', 'cartório'],
    group: 'Brasil',
    category: 'doc',
    description: 'Nascimento, casamento ou óbito — com matrícula e cartório.',
    icon: 'file',
    accent: '#c084fc',
    fields: [
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Nascimento · Casamento · Óbito' },
      { id: 'matricula', label: 'Matrícula', kind: 'text', hint: '32 dígitos das certidões novas', numeric: true },
      { id: 'cartorio', label: 'Cartório', kind: 'text' },
      { id: 'livro', label: 'Livro', kind: 'text' },
      { id: 'folha', label: 'Folha', kind: 'text' },
      { id: 'termo', label: 'Termo', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'apostilada', label: 'Apostila de Haia', kind: 'text', placeholder: 'Sim · Não · Nº da apostila' },
    ],
  },
  {
    id: 'br-antecedentes',
    namePlaceholder: 'Antecedentes — visto de trabalho',
    label: 'Certidão de antecedentes',
    keywords: ['nada consta', 'antecedentes criminais', 'polícia federal', 'registo criminal'],
    group: 'Brasil',
    category: 'doc',
    description: 'Antecedentes criminais — validade costuma ser de 90 dias.',
    icon: 'scale',
    accent: '#f87171',
    fields: [
      { id: 'orgao', label: 'Órgão', kind: 'text', placeholder: 'Polícia Federal · Polícia Civil' },
      { id: 'numero', label: 'Nº de controle', kind: 'text', numeric: true },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text' },
    ],
  },
  {
    id: 'br-ctps',
    namePlaceholder: 'Carteira de trabalho — Maria',
    label: 'Carteira de trabalho',
    keywords: ['CTPS', 'carteira assinada', 'carteira profissional'],
    group: 'Brasil',
    category: 'doc',
    description: 'CTPS física ou digital.',
    icon: 'file',
    accent: '#a3e635',
    fields: [
      { id: 'numero', label: 'Número', kind: 'text', numeric: true },
      { id: 'serie', label: 'Série', kind: 'text', numeric: true },
      { id: 'uf', label: 'UF', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
    ],
  },

  // ---- Geral --------------------------------------------------------------
  {
    id: 'passaporte',
    namePlaceholder: 'Passaporte — Maria',
    label: 'Passaporte',
    keywords: ['passport', 'viagem'],
    group: 'Geral',
    category: 'doc',
    description: 'Qualquer nacionalidade, uma entrada por emissão.',
    icon: 'passport',
    accent: '#5b8cff',
    fields: [
      { id: 'pais', label: 'País emissor', kind: 'text', placeholder: 'Brasil · Portugal' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Comum · Oficial' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'autoridade', label: 'Autoridade emissora', kind: 'text' },
      { id: 'localEmissao', label: 'Local de emissão', kind: 'text' },
    ],
  },
  {
    id: 'visto',
    namePlaceholder: 'Visto D7 — Portugal',
    label: 'Visto',
    keywords: ['visa', 'imigração', 'residência'],
    group: 'Geral',
    category: 'doc',
    description: 'Visto consular, com entradas e prazo.',
    icon: 'stamp',
    accent: '#22d3ee',
    fields: [
      { id: 'pais', label: 'País', kind: 'text' },
      { id: 'tipo', label: 'Tipo de visto', kind: 'text', placeholder: 'D7 · Schengen · Trabalho' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'entradas', label: 'Entradas', kind: 'text', placeholder: 'Múltiplas' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'declaracao-nado-vivo',
    namePlaceholder: 'Nascido vivo — Helena',
    family: 'declaracoes',
    label: 'Declaração de nascido vivo',
    keywords: [
      'nado vivo', 'nado-vivo', 'nato vivo', 'nascido vivo', 'DNV', 'declaração de nascimento', 'maternidade'
    ],
    group: 'Geral',
    category: 'doc',
    description: 'Da maternidade: nado-vivo em Portugal, nascido vivo (DNV) no Brasil.',
    icon: 'file',
    accent: '#f9a8d4',
    fields: [
      { id: 'numero', label: 'Nº da declaração', kind: 'text' },
      { id: 'maternidade', label: 'Hospital / maternidade', kind: 'text' },
      { id: 'nascimento', label: 'Nascimento', kind: 'text', placeholder: '2026-01-15 · 04:32' },
      { id: 'localNascimento', label: 'Local', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
    ],
  },
  {
    id: 'declaracao-credito-pessoal',
    namePlaceholder: 'Crédito pessoal — banco',
    family: 'declaracoes',
    label: 'Declaração de crédito pessoal',
    keywords: ['empréstimo', 'financiamento', 'dívida'],
    group: 'Geral',
    category: 'doc',
    description: 'Do banco: capital em dívida, prestação e taxa do crédito pessoal.',
    icon: 'file',
    accent: '#fbbf24',
    fields: [
      { id: 'banco', label: 'Banco', kind: 'text' },
      { id: 'contrato', label: 'Nº do contrato', kind: 'text' },
      { id: 'capitalEmDivida', label: 'Capital em dívida', kind: 'text', placeholder: '12 340,00 €' },
      { id: 'prestacao', label: 'Prestação mensal', kind: 'text' },
      { id: 'taxa', label: 'Taxa (TAN / TAEG)', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text' },
    ],
  },
  {
    id: 'declaracao-credito-hipotecario',
    namePlaceholder: 'Crédito habitação — banco',
    family: 'declaracoes',
    label: 'Declaração de crédito hipotecário',
    keywords: ['crédito habitação', 'financiamento imobiliário', 'hipoteca', 'dívida'],
    group: 'Geral',
    category: 'doc',
    description: 'Do banco: imóvel, capital em dívida e prestação do crédito habitação.',
    icon: 'file',
    accent: '#fb923c',
    fields: [
      { id: 'banco', label: 'Banco', kind: 'text' },
      { id: 'contrato', label: 'Nº do contrato', kind: 'text' },
      { id: 'imovel', label: 'Imóvel', kind: 'text', placeholder: 'Morada do imóvel hipotecado' },
      { id: 'capitalEmDivida', label: 'Capital em dívida', kind: 'text' },
      { id: 'prestacao', label: 'Prestação mensal', kind: 'text' },
      { id: 'taxa', label: 'Taxa (TAN / TAEG)', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text' },
    ],
  },
  {
    id: 'recibo-vencimento',
    namePlaceholder: 'Recibo — agosto/2026',
    label: 'Recibo de vencimento',
    keywords: ['holerite', 'contracheque', 'folha de pagamento', 'salário', 'payslip'],
    group: 'Geral',
    category: 'doc',
    description: 'Um por mês — holerite/contracheque no Brasil. Processos de crédito pedem os últimos três.',
    icon: 'note',
    accent: '#4ade80',
    fields: [
      { id: 'empregador', label: 'Empregador', kind: 'text' },
      { id: 'mes', label: 'Mês de referência', kind: 'text', placeholder: '2026-08' },
      { id: 'bruto', label: 'Vencimento bruto', kind: 'text' },
      { id: 'liquido', label: 'Líquido recebido', kind: 'text' },
    ],
  },
  {
    id: 'contrato-trabalho',
    namePlaceholder: 'Contrato de trabalho — 2026',
    label: 'Contrato de trabalho',
    keywords: ['CLT', 'emprego', 'empregador', 'employment'],
    group: 'Geral',
    category: 'doc',
    description: 'Empregador, função, tipo e datas — o termo certo entra nos alertas.',
    icon: 'badge',
    accent: '#60a5fa',
    fields: [
      { id: 'empregador', label: 'Empregador', kind: 'text' },
      { id: 'funcao', label: 'Função / cargo', kind: 'text' },
      { id: 'tipoContrato', label: 'Tipo de contrato', kind: 'text', placeholder: 'Sem termo · Termo certo · Recibos verdes' },
      { id: 'inicio', label: 'Início', kind: 'date' },
      { id: 'expiresAt', label: 'Termina em', kind: 'date', hint: 'Vazio para contratos sem termo' },
      { id: 'vencimento', label: 'Vencimento acordado', kind: 'text' },
    ],
  },
  {
    // Last resort only: the platform's promise is a SPECIFIC form per document
    // kind (see the types above). This one exists so an unforeseen declaration
    // still gets structured fields instead of a loose file.
    id: 'declaracao',
    namePlaceholder: 'Declaração — para que serve',
    family: 'declaracoes',
    label: 'Declaração',
    keywords: ['comprovativo', 'comprovante', 'certidão'],
    group: 'Geral',
    category: 'doc',
    description: 'Outra declaração que ainda não tem formulário próprio.',
    icon: 'file',
    accent: '#e8b45a',
    fields: [
      { id: 'tipo', label: 'Tipo de declaração', kind: 'text' },
      { id: 'entidade', label: 'Entidade emissora', kind: 'text', placeholder: 'AT · Segurança Social · Banco · Hospital' },
      { id: 'numero', label: 'Número / referência', kind: 'text' },
      { id: 'codigoValidacao', label: 'Código de validação', kind: 'secret', hint: 'Recupera o documento online, quando existir' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date', hint: 'Vazio se não expira' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text', placeholder: 'Crédito habitação · Matrícula · Concurso' },
    ],
  },
  {
    id: 'diploma',
    namePlaceholder: 'Licenciatura — Engenharia',
    label: 'Habilitações',
    keywords: ['diploma', 'certificado', 'faculdade', 'universidade', 'graduação', 'licenciatura'],
    group: 'Geral',
    category: 'doc',
    description: 'Diploma, histórico e reconhecimento/equivalência.',
    icon: 'diploma',
    accent: '#fb923c',
    fields: [
      { id: 'instituicao', label: 'Instituição', kind: 'text' },
      { id: 'curso', label: 'Curso', kind: 'text' },
      { id: 'grau', label: 'Grau', kind: 'text', placeholder: 'Licenciatura · Mestrado' },
      { id: 'conclusao', label: 'Concluído em', kind: 'date' },
      { id: 'reconhecimento', label: 'Reconhecimento / equivalência', kind: 'text' },
    ],
  },
  {
    id: 'vacinacao',
    namePlaceholder: 'Vacinação — Helena',
    label: 'Vacinação',
    keywords: ['carteira de vacinação', 'boletim de vacinas', 'vacina', 'imunização'],
    group: 'Geral',
    category: 'doc',
    description: 'Boletim ou certificado de vacinas.',
    icon: 'health',
    accent: '#34d399',
    fields: [
      { id: 'vacina', label: 'Vacina', kind: 'text' },
      { id: 'doses', label: 'Doses', kind: 'multiline', placeholder: '1ª dose 10/01/2024 — lote ABC' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'seguro-saude',
    namePlaceholder: 'Seguro de saúde — apólice 2026',
    label: 'Seguro / saúde',
    keywords: ['plano de saúde', 'convênio', 'apólice'],
    group: 'Geral',
    category: 'doc',
    description: 'Apólice de seguro ou plano de saúde.',
    icon: 'health',
    accent: '#f472b6',
    fields: [
      { id: 'seguradora', label: 'Seguradora / operadora', kind: 'text' },
      { id: 'apolice', label: 'Apólice / nº de adesão', kind: 'text' },
      { id: 'cobertura', label: 'Cobertura', kind: 'text' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'contactoUrgencia', label: 'Contacto de urgência', kind: 'text' },
    ],
  },
  {
    id: 'cartao-credito',
    namePlaceholder: 'Cartão principal',
    label: 'Cartão de crédito',
    keywords: ['cartão de débito', 'multibanco'],
    group: 'Geral',
    category: 'doc',
    description: 'Número, CVC e PIN ocultos; validade com alerta de vencimento.',
    icon: 'creditCard',
    accent: '#fb7185',
    fields: [
      { id: 'holder', label: 'Nome no cartão', kind: 'text' },
      { id: 'number', label: 'Número do cartão', kind: 'secret', numeric: true },
      { id: 'brand', label: 'Bandeira', kind: 'text', placeholder: 'Visa · Mastercard · Amex' },
      {
        id: 'expiresAt',
        label: 'Válido até (fim do mês)',
        kind: 'date',
        hint: 'O cartão vale até o fim do mês impresso — entra nos alertas.',
      },
      { id: 'cvc', label: 'CVC', kind: 'secret', numeric: true },
      { id: 'pin', label: 'PIN', kind: 'secret', numeric: true },
      { id: 'password', label: 'Senha (app / compras online)', kind: 'password' },
      { id: 'issuer', label: 'Banco / emissor', kind: 'text' },
      // Presentation, not data: a preset name or a hex; the detail's card
      // visual consumes it and the editor renders a swatch picker for it.
      { id: 'cardColor', label: 'Cor do cartão', kind: 'text' },
    ],
  },
  {
    id: 'documento',
    namePlaceholder: 'Outro documento — 2026',
    label: 'Outro documento',
    group: 'Geral',
    category: 'doc',
    description: 'Para o que não se encaixa nos tipos acima.',
    icon: 'file',
    accent: '#94a3b8',
    fields: [
      { id: 'pais', label: 'País', kind: 'text' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },

  // ---- Portugal (expansion) ----
  {
    id: 'pt-carta-conducao',
    namePlaceholder: 'Carta de condução — Maria',
    label: 'Carta de Condução',
    keywords: ['carteira de motorista', 'CNH', 'habilitação', 'IMT'],
    group: 'Portugal',
    category: 'doc',
    description: 'Carta portuguesa: categorias, emissão e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Nº da carta', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B · A1' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'entidade', label: 'Entidade', kind: 'text', placeholder: 'IMT' },
    ],
  },
  {
    id: 'pt-certidao',
    namePlaceholder: 'Certidão de nascimento — Helena',
    label: 'Certidão (registo civil)',
    keywords: ['certidão de nascimento', 'certidão de casamento', 'conservatória'],
    group: 'Portugal',
    category: 'doc',
    description: 'Nascimento ou casamento — com conservatória e código de acesso.',
    icon: 'file',
    accent: '#c084fc',
    fields: [
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Nascimento · Casamento' },
      { id: 'conservatoria', label: 'Conservatória', kind: 'text' },
      { id: 'assento', label: 'Nº do assento', kind: 'text', numeric: true },
      { id: 'ano', label: 'Ano', kind: 'text', numeric: true },
      { id: 'codigoAcesso', label: 'Código de acesso', kind: 'secret', hint: 'Da certidão permanente online' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
    ],
  },
  {
    id: 'pt-irs',
    namePlaceholder: 'IRS 2025',
    family: 'declaracoes',
    label: 'Declaração de IRS',
    keywords: ['imposto de renda', 'IRPF', 'modelo 3', 'finanças', 'fisco', 'AT'],
    group: 'Portugal',
    category: 'doc',
    description: 'Modelo 3 e nota de liquidação do ano fiscal.',
    icon: 'file',
    accent: '#38bdf8',
    fields: [
      { id: 'ano', label: 'Ano fiscal', kind: 'text', numeric: true, placeholder: '2025' },
      { id: 'numeroDeclaracao', label: 'Nº da declaração', kind: 'text' },
      { id: 'dataEntrega', label: 'Entregue em', kind: 'date' },
      { id: 'resultado', label: 'Resultado', kind: 'text', placeholder: 'Reembolso 512 € · A pagar 210 €' },
      { id: 'codigoValidacao', label: 'Código de validação', kind: 'secret', hint: 'Do comprovativo de entrega' },
    ],
  },
  {
    id: 'pt-situacao-contributiva',
    namePlaceholder: 'Situação contributiva — 2026',
    family: 'declaracoes',
    label: 'Situação contributiva',
    keywords: ['certidão negativa', 'não dívida', 'segurança social', 'INSS'],
    group: 'Portugal',
    category: 'doc',
    description: 'Declaração da Segurança Social, com prazo de validade.',
    icon: 'file',
    accent: '#2dd4bf',
    fields: [
      { id: 'niss', label: 'NISS', kind: 'text', numeric: true },
      { id: 'numero', label: 'Nº / referência', kind: 'text' },
      { id: 'situacao', label: 'Situação', kind: 'text', placeholder: 'Regularizada' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'codigoValidacao', label: 'Código de validação', kind: 'secret' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text', placeholder: 'Crédito habitação · Concurso' },
    ],
  },
  {
    id: 'pt-situacao-tributaria',
    namePlaceholder: 'Situação tributária — 2026',
    family: 'declaracoes',
    label: 'Situação tributária',
    keywords: ['certidão negativa', 'não dívida', 'finanças', 'fisco', 'AT'],
    group: 'Portugal',
    category: 'doc',
    description: 'Certidão de não dívida da AT — o par da contributiva em qualquer processo.',
    icon: 'file',
    accent: '#a78bfa',
    fields: [
      { id: 'nif', label: 'NIF', kind: 'text', numeric: true },
      { id: 'numero', label: 'Nº / referência', kind: 'text' },
      { id: 'situacao', label: 'Situação', kind: 'text', placeholder: 'Regularizada' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'codigoValidacao', label: 'Código de validação', kind: 'secret' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text' },
    ],
  },
  {
    id: 'pt-imi',
    namePlaceholder: 'IMI 2026 — Rua das Flores',
    label: 'IMI',
    keywords: ['IPTU', 'imposto municipal', 'imóvel', 'habitação'],
    group: 'Portugal',
    category: 'doc',
    description: 'Nota de cobrança anual do imóvel — VPT, valor e prestações.',
    icon: 'home',
    accent: '#f472b6',
    fields: [
      { id: 'ano', label: 'Ano', kind: 'text', numeric: true },
      { id: 'imovel', label: 'Imóvel', kind: 'text', placeholder: 'Morada · artigo matricial' },
      { id: 'vpt', label: 'Valor patrimonial (VPT)', kind: 'text' },
      { id: 'valor', label: 'Valor do imposto', kind: 'text' },
      { id: 'prestacoes', label: 'Prestações', kind: 'text', placeholder: 'Maio · Agosto · Novembro' },
      { id: 'expiresAt', label: 'Pagar até', kind: 'date', hint: 'Prazo da próxima prestação — alimenta os alertas' },
      { id: 'referencia', label: 'Referência de pagamento', kind: 'text' },
    ],
  },

  // ---- Espanha ----
  {
    id: 'es-dni',
    namePlaceholder: 'DNI — Maria',
    label: 'DNI',
    keywords: ['identidade', 'documento de identidade'],
    group: 'Espanha',
    category: 'doc',
    description: 'Documento Nacional de Identidad.',
    icon: 'idCard',
    accent: '#c084fc',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text', placeholder: '12345678Z' },
      { id: 'issuedAt', label: 'Expedido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'es-nie',
    namePlaceholder: 'NIE — Maria',
    label: 'NIE / TIE',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'Espanha',
    category: 'doc',
    description: 'Número de estrangeiro e o cartão TIE, com validade.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'nie', label: 'NIE', kind: 'text', placeholder: 'X1234567Z' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'TIE · Certificado UE' },
      { id: 'issuedAt', label: 'Expedido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'es-nss',
    namePlaceholder: 'Seguridad Social — Maria',
    label: 'Seguridad Social',
    keywords: ['segurança social'],
    group: 'Espanha',
    category: 'doc',
    description: 'Número de la Seguridad Social.',
    icon: 'badge',
    accent: '#fbbf24',
    fields: [{ id: 'numero', label: 'Número', kind: 'text', numeric: true }],
  },
  {
    id: 'es-conducir',
    namePlaceholder: 'Permiso de conducir — Maria',
    label: 'Permiso de Conducir',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'Espanha',
    category: 'doc',
    description: 'Carta espanhola: categorias e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B' },
      { id: 'issuedAt', label: 'Expedido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },

  // ---- Estados Unidos ----
  {
    id: 'us-ssn',
    namePlaceholder: 'SSN — Maria',
    label: 'Social Security Number',
    keywords: ['social security', 'número fiscal'],
    group: 'Estados Unidos',
    category: 'doc',
    description: 'SSN — tratado como segredo.',
    icon: 'badge',
    accent: '#38bdf8',
    fields: [{ id: 'ssn', label: 'SSN', kind: 'secret', placeholder: '123-45-6789' }],
  },
  {
    id: 'us-green-card',
    namePlaceholder: 'Green Card — Maria',
    label: 'Green Card',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'Estados Unidos',
    category: 'doc',
    description: 'Permanent Resident Card, com A-Number e validade.',
    icon: 'idCard',
    accent: '#34d399',
    fields: [
      { id: 'aNumber', label: 'A-Number', kind: 'text', placeholder: 'A123456789' },
      { id: 'cardNumber', label: 'Card number', kind: 'text' },
      { id: 'category', label: 'Categoria', kind: 'text', placeholder: 'IR1 · EB2' },
      { id: 'issuedAt', label: 'Resident since', kind: 'date' },
      { id: 'expiresAt', label: 'Card expires', kind: 'date' },
    ],
  },
  {
    id: 'us-driver-license',
    namePlaceholder: 'Driver’s License — Maria',
    label: 'Driver’s License',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'Estados Unidos',
    category: 'doc',
    description: 'Carteira estadual: estado, classe e validade.',
    icon: 'car',
    accent: '#f472b6',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'estado', label: 'Estado', kind: 'text', placeholder: 'CA' },
      { id: 'classe', label: 'Classe', kind: 'text', placeholder: 'C' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Expira em', kind: 'date' },
    ],
  },

  // ---- França ----
  {
    id: 'fr-cni',
    namePlaceholder: 'CNI — Maria',
    label: 'Carte d’Identité',
    keywords: ['identidade', 'documento de identidade'],
    group: 'França',
    category: 'doc',
    description: 'Carte Nationale d’Identité.',
    icon: 'idCard',
    accent: '#f472b6',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
    ],
  },
  {
    id: 'fr-titre-sejour',
    namePlaceholder: 'Titre de séjour — Maria',
    label: 'Titre de Séjour',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'França',
    category: 'doc',
    description: 'Autorização de residência francesa, com validade.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Vie privée · Salarié · Passeport talent' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'fr-secu',
    namePlaceholder: 'Sécurité Sociale — Maria',
    label: 'Sécurité Sociale',
    keywords: ['segurança social'],
    group: 'França',
    category: 'doc',
    description: 'Numéro de Sécurité Sociale (15 dígitos).',
    icon: 'health',
    accent: '#fbbf24',
    fields: [{ id: 'numero', label: 'Número', kind: 'text', numeric: true }],
  },
  {
    id: 'fr-permis',
    namePlaceholder: 'Permis — Maria',
    label: 'Permis de Conduire',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'França',
    category: 'doc',
    description: 'Carta francesa: categorias e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },

  // ---- Alemanha ----
  {
    id: 'de-personalausweis',
    namePlaceholder: 'Personalausweis — Maria',
    label: 'Personalausweis',
    keywords: ['identidade', 'documento de identidade'],
    group: 'Alemanha',
    category: 'doc',
    description: 'Documento de identidade alemão.',
    icon: 'idCard',
    accent: '#a3e635',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'de-aufenthaltstitel',
    namePlaceholder: 'Aufenthaltstitel — Maria',
    label: 'Aufenthaltstitel',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'Alemanha',
    category: 'doc',
    description: 'Autorização de residência alemã, com validade.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Blaue Karte · Niederlassungserlaubnis' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'de-steuer-id',
    namePlaceholder: 'Steuer-ID — Maria',
    label: 'Steuer-ID',
    keywords: ['número fiscal', 'contribuinte'],
    group: 'Alemanha',
    category: 'doc',
    description: 'Identificação fiscal alemã (11 dígitos).',
    icon: 'stamp',
    accent: '#fbbf24',
    fields: [{ id: 'numero', label: 'Número', kind: 'text', numeric: true }],
  },
  {
    id: 'de-fuehrerschein',
    namePlaceholder: 'Führerschein — Maria',
    label: 'Führerschein',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'Alemanha',
    category: 'doc',
    description: 'Carta alemã: categorias e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
    ],
  },

  // ---- Itália ----
  {
    id: 'it-carta-identita',
    namePlaceholder: 'Carta d’identità — Maria',
    label: 'Carta d’Identità',
    keywords: ['identidade', 'documento de identidade'],
    group: 'Itália',
    category: 'doc',
    description: 'Carta d’Identità Elettronica (CIE).',
    icon: 'idCard',
    accent: '#22d3ee',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
    ],
  },
  {
    id: 'it-codice-fiscale',
    namePlaceholder: 'Codice fiscale — Maria',
    label: 'Codice Fiscale',
    keywords: ['número fiscal', 'contribuinte'],
    group: 'Itália',
    category: 'doc',
    description: 'Identificação fiscal italiana (alfanumérica).',
    icon: 'diploma',
    accent: '#fbbf24',
    fields: [{ id: 'codice', label: 'Codice', kind: 'text', placeholder: 'RSSMRA80A01H501U' }],
  },
  {
    id: 'it-permesso',
    namePlaceholder: 'Permesso — Maria',
    label: 'Permesso di Soggiorno',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'Itália',
    category: 'doc',
    description: 'Autorização de residência italiana, com validade.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'motivo', label: 'Motivo', kind: 'text', placeholder: 'Lavoro · Famiglia · Studio' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'it-patente',
    namePlaceholder: 'Patente — Maria',
    label: 'Patente di Guida',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'Itália',
    category: 'doc',
    description: 'Carta italiana: categorias e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
    ],
  },

  // ---- Reino Unido ----
  {
    id: 'gb-ni-number',
    namePlaceholder: 'NI Number — Maria',
    label: 'National Insurance Number',
    keywords: ['segurança social', 'número fiscal'],
    group: 'Reino Unido',
    category: 'doc',
    description: 'NI Number britânico.',
    icon: 'badge',
    accent: '#7c9cff',
    fields: [{ id: 'nino', label: 'NI Number', kind: 'text', placeholder: 'QQ 12 34 56 C' }],
  },
  {
    id: 'gb-brp',
    namePlaceholder: 'BRP — Maria',
    label: 'BRP / eVisa',
    keywords: ['residência', 'imigração', 'autorização de residência'],
    group: 'Reino Unido',
    category: 'doc',
    description: 'Residência britânica: BRP ou eVisa, com validade.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número / share code', kind: 'text' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'BRP · eVisa' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'gb-driving-licence',
    namePlaceholder: 'Driving Licence — Maria',
    label: 'Driving Licence',
    keywords: ['carteira de motorista', 'carta de condução', 'habilitação'],
    group: 'Reino Unido',
    category: 'doc',
    description: 'Carta britânica: categorias e validade.',
    icon: 'car',
    accent: '#38bdf8',
    fields: [
      { id: 'documentNumber', label: 'Número', kind: 'text' },
      { id: 'categorias', label: 'Categorias', kind: 'text', placeholder: 'B' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
    ],
  },
];
