/**
 * Personal document types, grouped by the country that issues them.
 *
 * These are deliberately specific: a residence permit and a birth certificate
 * have almost nothing in common beyond "it is paper", and typing the issuing
 * authority into a generic "notes" box is how a document becomes unfindable
 * three years later. Fields left blank never render, so a rich schema costs
 * nothing to whoever only fills two of them.
 *
 * Credentials are deliberately absent — a tax-portal password belongs in the
 * `login` type, which tracks 2FA and rotates on its own cadence.
 */
import type { SecretTypeDef } from './model';

export const DOCUMENT_TYPES: SecretTypeDef[] = [
  // ---- Portugal -----------------------------------------------------------
  {
    id: 'pt-residencia',
    label: 'Título de residência',
    group: 'Portugal',
    category: 'doc',
    description: 'Autorização de residência emitida pela AIMA/SEF, por emissão.',
    icon: 'idCard',
    accent: '#34d399',
    fields: [
      { id: 'documentNumber', label: 'Número do título', kind: 'text' },
      { id: 'tipoAutorizacao', label: 'Tipo de autorização', kind: 'text', placeholder: 'Temporária · Permanente · CPLP' },
      { id: 'entidade', label: 'Entidade emissora', kind: 'text', placeholder: 'AIMA' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'processo', label: 'Número do processo', kind: 'text' },
      { id: 'observacoes', label: 'Observações', kind: 'multiline' },
    ],
  },
  {
    id: 'pt-cartao-cidadao',
    label: 'Cartão de Cidadão',
    group: 'Portugal',
    category: 'doc',
    description: 'Documento de identificação português, com os números que ele agrega.',
    icon: 'idCard',
    accent: '#22d3ee',
    fields: [
      { id: 'civilId', label: 'Nº de identificação civil', kind: 'text' },
      { id: 'documentNumber', label: 'Nº do documento', kind: 'text', hint: 'Inclui a versão, ex.: 12345678 9 ZZ1' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'nif', label: 'NIF', kind: 'text' },
      { id: 'niss', label: 'NISS', kind: 'text' },
      { id: 'sns', label: 'Nº de utente (SNS)', kind: 'text' },
    ],
  },
  {
    id: 'pt-nif',
    label: 'NIF',
    group: 'Portugal',
    category: 'doc',
    description: 'Número de identificação fiscal português.',
    icon: 'stamp',
    accent: '#fbbf24',
    fields: [
      { id: 'nif', label: 'NIF', kind: 'text', placeholder: '123456789' },
      { id: 'servicoFinancas', label: 'Serviço de finanças', kind: 'text' },
      { id: 'representante', label: 'Representante fiscal', kind: 'text' },
      { id: 'issuedAt', label: 'Atribuído em', kind: 'date' },
    ],
  },
  {
    id: 'pt-niss',
    label: 'NISS',
    group: 'Portugal',
    category: 'doc',
    description: 'Número de identificação da Segurança Social.',
    icon: 'stamp',
    accent: '#a3e635',
    fields: [
      { id: 'niss', label: 'NISS', kind: 'text' },
      { id: 'issuedAt', label: 'Atribuído em', kind: 'date' },
    ],
  },
  {
    id: 'pt-utente',
    label: 'Nº de utente (SNS)',
    group: 'Portugal',
    category: 'doc',
    description: 'Número de utente do Serviço Nacional de Saúde.',
    icon: 'health',
    accent: '#f472b6',
    fields: [
      { id: 'numeroUtente', label: 'Nº de utente', kind: 'text' },
      { id: 'centroSaude', label: 'Centro de saúde', kind: 'text' },
      { id: 'medicoFamilia', label: 'Médico de família', kind: 'text' },
    ],
  },
  {
    id: 'pt-registo-criminal',
    label: 'Registo criminal',
    group: 'Portugal',
    category: 'doc',
    description: 'Certificado de registo criminal — costuma ter validade curta.',
    icon: 'scale',
    accent: '#c084fc',
    fields: [
      { id: 'documentNumber', label: 'Nº do certificado', kind: 'text' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text', placeholder: 'Nacionalidade · Emprego' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'pt-morada',
    label: 'Comprovativo de morada',
    group: 'Portugal',
    category: 'doc',
    description: 'Atestado de junta de freguesia, fatura ou equivalente.',
    icon: 'home',
    accent: '#7c9cff',
    fields: [
      { id: 'tipoComprovativo', label: 'Tipo', kind: 'text', placeholder: 'Atestado de residência · Fatura' },
      { id: 'morada', label: 'Morada', kind: 'multiline' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
    ],
  },
  {
    id: 'pt-arrendamento',
    label: 'Contrato de arrendamento',
    group: 'Portugal',
    category: 'doc',
    description: 'Contrato de habitação, com prazos e renda.',
    icon: 'home',
    accent: '#fb923c',
    fields: [
      { id: 'morada', label: 'Morada', kind: 'multiline' },
      { id: 'senhorio', label: 'Senhorio', kind: 'text' },
      { id: 'contractNumber', label: 'Nº do contrato / recibo', kind: 'text' },
      { id: 'startsAt', label: 'Início', kind: 'date' },
      { id: 'endsAt', label: 'Fim', kind: 'date' },
      { id: 'renda', label: 'Renda mensal', kind: 'text' },
    ],
  },

  // ---- Brasil -------------------------------------------------------------
  {
    id: 'br-cpf',
    label: 'CPF',
    group: 'Brasil',
    category: 'doc',
    description: 'Cadastro de Pessoas Físicas.',
    icon: 'stamp',
    accent: '#34d399',
    fields: [
      { id: 'cpf', label: 'CPF', kind: 'text', placeholder: '000.000.000-00' },
      { id: 'situacao', label: 'Situação cadastral', kind: 'text', placeholder: 'Regular' },
      { id: 'issuedAt', label: 'Inscrição em', kind: 'date' },
    ],
  },
  {
    id: 'br-rg',
    label: 'RG',
    group: 'Brasil',
    category: 'doc',
    description: 'Registro Geral / carteira de identidade.',
    icon: 'idCard',
    accent: '#38bdf8',
    fields: [
      { id: 'rgNumber', label: 'Número', kind: 'text' },
      { id: 'orgaoEmissor', label: 'Órgão emissor', kind: 'text', placeholder: 'SSP' },
      { id: 'uf', label: 'UF', kind: 'text', placeholder: 'RJ' },
      { id: 'issuedAt', label: 'Data de expedição', kind: 'date' },
    ],
  },
  {
    id: 'br-cnh',
    label: 'CNH',
    group: 'Brasil',
    category: 'doc',
    description: 'Carteira Nacional de Habilitação.',
    icon: 'car',
    accent: '#fbbf24',
    fields: [
      { id: 'registro', label: 'Nº de registro', kind: 'text' },
      { id: 'numeroEspelho', label: 'Nº do espelho', kind: 'text' },
      { id: 'categoria', label: 'Categoria', kind: 'text', placeholder: 'AB' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'primeiraHabilitacao', label: 'Primeira habilitação', kind: 'date' },
    ],
  },
  {
    id: 'br-titulo-eleitor',
    label: 'Título de eleitor',
    group: 'Brasil',
    category: 'doc',
    description: 'Inscrição eleitoral, zona e seção.',
    icon: 'stamp',
    accent: '#818cf8',
    fields: [
      { id: 'numero', label: 'Nº de inscrição', kind: 'text' },
      { id: 'zona', label: 'Zona', kind: 'text' },
      { id: 'secao', label: 'Seção', kind: 'text' },
      { id: 'municipio', label: 'Município', kind: 'text' },
      { id: 'uf', label: 'UF', kind: 'text' },
    ],
  },
  {
    id: 'br-certidao',
    label: 'Certidão de registo civil',
    group: 'Brasil',
    category: 'doc',
    description: 'Nascimento, casamento ou óbito — com matrícula e cartório.',
    icon: 'file',
    accent: '#c084fc',
    fields: [
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Nascimento · Casamento · Óbito' },
      { id: 'matricula', label: 'Matrícula', kind: 'text', hint: '32 dígitos das certidões novas' },
      { id: 'cartorio', label: 'Cartório', kind: 'text' },
      { id: 'livro', label: 'Livro', kind: 'text' },
      { id: 'folha', label: 'Folha', kind: 'text' },
      { id: 'termo', label: 'Termo', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'apostilada', label: 'Apostila de Haia', kind: 'text', placeholder: 'Sim · Não · Nº da apostila' },
    ],
  },
  {
    id: 'br-antecedentes',
    label: 'Certidão de antecedentes',
    group: 'Brasil',
    category: 'doc',
    description: 'Antecedentes criminais — validade costuma ser de 90 dias.',
    icon: 'scale',
    accent: '#f87171',
    fields: [
      { id: 'orgao', label: 'Órgão', kind: 'text', placeholder: 'Polícia Federal · Polícia Civil' },
      { id: 'numero', label: 'Nº de controle', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
      { id: 'expiresAt', label: 'Válida até', kind: 'date' },
      { id: 'finalidade', label: 'Finalidade', kind: 'text' },
    ],
  },
  {
    id: 'br-ctps',
    label: 'Carteira de trabalho',
    group: 'Brasil',
    category: 'doc',
    description: 'CTPS física ou digital.',
    icon: 'file',
    accent: '#a3e635',
    fields: [
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'serie', label: 'Série', kind: 'text' },
      { id: 'uf', label: 'UF', kind: 'text' },
      { id: 'issuedAt', label: 'Emitida em', kind: 'date' },
    ],
  },

  // ---- Geral --------------------------------------------------------------
  {
    id: 'passaporte',
    label: 'Passaporte',
    group: 'Geral',
    category: 'doc',
    description: 'Qualquer nacionalidade, uma entrada por emissão.',
    icon: 'passport',
    accent: '#5b8cff',
    fields: [
      { id: 'pais', label: 'País emissor', kind: 'text', placeholder: 'Brasil · Portugal' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'tipo', label: 'Tipo', kind: 'text', placeholder: 'Comum · Oficial' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'autoridade', label: 'Autoridade emissora', kind: 'text' },
      { id: 'localEmissao', label: 'Local de emissão', kind: 'text' },
    ],
  },
  {
    id: 'visto',
    label: 'Visto',
    group: 'Geral',
    category: 'doc',
    description: 'Visto consular, com entradas e prazo.',
    icon: 'stamp',
    accent: '#22d3ee',
    fields: [
      { id: 'pais', label: 'País', kind: 'text' },
      { id: 'tipo', label: 'Tipo de visto', kind: 'text', placeholder: 'D7 · Schengen · Trabalho' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'entradas', label: 'Entradas', kind: 'text', placeholder: 'Múltiplas' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'diploma',
    label: 'Habilitações',
    group: 'Geral',
    category: 'doc',
    description: 'Diploma, histórico e reconhecimento/equivalência.',
    icon: 'diploma',
    accent: '#fb923c',
    fields: [
      { id: 'instituicao', label: 'Instituição', kind: 'text' },
      { id: 'curso', label: 'Curso', kind: 'text' },
      { id: 'grau', label: 'Grau', kind: 'text', placeholder: 'Licenciatura · Mestrado' },
      { id: 'conclusao', label: 'Concluído em', kind: 'date' },
      { id: 'reconhecimento', label: 'Reconhecimento / equivalência', kind: 'text' },
    ],
  },
  {
    id: 'vacinacao',
    label: 'Vacinação',
    group: 'Geral',
    category: 'doc',
    description: 'Boletim ou certificado de vacinas.',
    icon: 'health',
    accent: '#34d399',
    fields: [
      { id: 'vacina', label: 'Vacina', kind: 'text' },
      { id: 'doses', label: 'Doses', kind: 'multiline', placeholder: '1ª dose 10/01/2024 — lote ABC' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
  {
    id: 'seguro-saude',
    label: 'Seguro / saúde',
    group: 'Geral',
    category: 'doc',
    description: 'Apólice de seguro ou plano de saúde.',
    icon: 'health',
    accent: '#f472b6',
    fields: [
      { id: 'seguradora', label: 'Seguradora / operadora', kind: 'text' },
      { id: 'apolice', label: 'Apólice / nº de adesão', kind: 'text' },
      { id: 'cobertura', label: 'Cobertura', kind: 'text' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
      { id: 'contactoUrgencia', label: 'Contacto de urgência', kind: 'text' },
    ],
  },
  {
    id: 'documento',
    label: 'Outro documento',
    group: 'Geral',
    category: 'doc',
    description: 'Para o que não se encaixa nos tipos acima.',
    icon: 'file',
    accent: '#94a3b8',
    fields: [
      { id: 'pais', label: 'País', kind: 'text' },
      { id: 'numero', label: 'Número', kind: 'text' },
      { id: 'entidade', label: 'Emitido por', kind: 'text' },
      { id: 'issuedAt', label: 'Emitido em', kind: 'date' },
      { id: 'expiresAt', label: 'Válido até', kind: 'date' },
    ],
  },
];
